runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'busymind@25'
  INSTANCE_CONNECTION_NAME: 'eiu-strapi-blog:us-central1:eiu-strapi-blog'

beta_settings:
  cloud_sql_instances: 'eiu-strapi-blog:us-central1:eiu-strapi-blog'
